In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("thedevastator/billboard-hot-100-audio-features")

print("Path to dataset files:", path)

Downloading to /Users/manavdesai/.cache/kagglehub/datasets/thedevastator/billboard-hot-100-audio-features/1.archive...

100%|██████████| 13.4M/13.4M [00:01<00:00, 9.16MB/s]

Extracting files...
Path to dataset files: /Users/manavdesai/.cache/kagglehub/datasets/thedevastator/billboard-hot-100-audio-features/versions/1

In [2]:
import os

# List what's actually inside the downloaded folder
files = os.listdir(path)
print(files)

['Hot Stuff.csv', 'Hot 100 Audio Features.csv']

In [5]:
import pandas as pd

chart_history = pd.read_csv(os.path.join(path, "Hot Stuff.csv"))
audio_features = pd.read_csv(os.path.join(path, "Hot 100 Audio Features.csv" ))

In [7]:
print ("chart history shape:" , chart_history.shape)
print ("audio features shape:" , audio_features.shape)

print ("chart history header:" , chart_history.head)
print ("audio features header:" , audio_features.head)

chart history shape: (327895, 11)
audio features shape: (29503, 23)
chart history header: <bound method NDFrame.head of          index                                                url      WeekID  \
0            0  http://www.billboard.com/charts/hot-100/1965-0...   7/17/1965
1            1  http://www.billboard.com/charts/hot-100/1965-0...   7/24/1965
2            2  http://www.billboard.com/charts/hot-100/1965-0...   7/31/1965
3            3  http://www.billboard.com/charts/hot-100/1965-0...    8/7/1965
4            4  http://www.billboard.com/charts/hot-100/1965-0...   8/14/1965
...        ...                                                ...         ...
327890  327890  https://www.billboard.com/charts/hot-100/2018-...  10/20/2018
327891  327891  http://www.billboard.com/charts/hot-100/1977-0...   5/21/1977
327892  327892  http://www.billboard.com/charts/hot-100/1981-0...   5/23/1981
327893  327893  http://www.billboard.com/charts/hot-100/1973-0...   9/29/1973
327894  327894  https://www.billboard.com/charts/hot-100/2020-...  11/28/2020

        Week Position                      Song                  Performer  \
0                  34    Don't Just Stand There                 Patty Duke
1                  22    Don't Just Stand There                 Patty Duke
2                  14    Don't Just Stand There                 Patty Duke
3                  10    Don't Just Stand There                 Patty Duke
4                   8    Don't Just Stand There                 Patty Duke
...               ...                       ...                        ...
327890             22            God Is A Woman              Ariana Grande
327891             22   I Wanna Get Next To You                 Rose Royce
327892             22          I Can't Stand It  Eric Clapton And His Band
327893             22  Here I Am Come & Take Me                   Al Green
327894             22                     Hawai        Maluma & The Weeknd

                                           SongID  Instance  \
0                Don't Just Stand TherePatty Duke         1
1                Don't Just Stand TherePatty Duke         1
2                Don't Just Stand TherePatty Duke         1
3                Don't Just Stand TherePatty Duke         1
4                Don't Just Stand TherePatty Duke         1
...                                           ...       ...
327890                God Is A WomanAriana Grande         1
327891          I Wanna Get Next To YouRose Royce         1
327892  I Can't Stand ItEric Clapton And His Band         1
327893           Here I Am Come & Take MeAl Green         1
327894                   HawaiMaluma & The Weeknd         1

        Previous Week Position  Peak Position  Weeks on Chart
0                         45.0             34               4
1                         34.0             22               5
2                         22.0             14               6
3                         14.0             10               7
4                         10.0              8               8
...                        ...            ...             ...
327890                    21.0              8              13
327891                    10.0             10              13
327892                    12.0             10              13
327893                    16.0             10              13
327894                    12.0             12              13

[327895 rows x 11 columns]>
audio features header: <bound method NDFrame.head of        index                                             SongID  \
0          0     -twistin'-White Silver SandsBill Black's Combo
1          1  ¿Dònde Està Santa Claus? (Where Is Santa Claus...
2          2             ......And Roses And RosesAndy Williams
3          3           ...And Then There Were DrumsSandy Nelson
4          4                ...Baby One More TimeBritney Spears
...      ...                                                ...
29498  29498  Zoo YorkLil Tjay Featuring Fivio Foreign & Pop...
29499  29499                                         ZoomFuture
29500  29500                 ZoomLil' Boosie Featuring Yung Joc
29501  29501     Zorba The GreekHerb Alpert & The Tijuana Brass
29502  29502                                       Zunga ZengK7

                                          Performer  \
0                                Bill Black's Combo
1                                        Augie Rios
2                                     Andy Williams
3                                      Sandy Nelson
4                                    Britney Spears
...                                             ...
29498  Lil Tjay Featuring Fivio Foreign & Pop Smoke
29499                                        Future
29500                Lil' Boosie Featuring Yung Joc
29501               Herb Alpert & The Tijuana Brass
29502                                            K7

                                                   Song  \
0                          -twistin'-White Silver Sands
1      ¿Dònde Està Santa Claus? (Where Is Santa Claus?)
2                             ......And Roses And Roses
3                          ...And Then There Were Drums
4                                 ...Baby One More Time
...                                                 ...
29498                                          Zoo York
29499                                              Zoom
29500                                              Zoom
29501                                   Zorba The Greek
29502                                        Zunga Zeng

                                           spotify_genre  \
0                                                     []
1                                            ['novelty']
2      ['adult standards', 'brill building pop', 'eas...
3       ['rock-and-roll', 'space age pop', 'surf music']
4                  ['dance pop', 'pop', 'post-teen pop']
...                                                  ...
29498                                                NaN
29499  ['atl hip hop', 'hip hop', 'pop rap', 'rap', '...
29500          ['baton rouge rap', 'deep southern trap']
29501    ['adult standards', 'easy listening', 'lounge']
29502                                      ['freestyle']

             spotify_track_id  \
0                         NaN
1                         NaN
2      3tvqPPpXyIgKrm4PR9HCf0
3      1fHHq3qHU8wpRKHzhojZ4a
4      3MjUtNVVq3C8Fn0MP3zhXa
...                       ...
29498                     NaN
29499  2IG6Te7JyvrtqhFeOF7le4
29500                     NaN
29501  3WLEVNohakzZmMpN5W7mHK
29502  0XevPPcCBPovknaBw3lFvh

                               spotify_track_preview_url  \
0                                                    NaN
1                                                    NaN
2      https://p.scdn.co/mp3-preview/cef4883cfd1e0e53...
3                                                    NaN
4      https://p.scdn.co/mp3-preview/da2134a161f1cb34...
...                                                  ...
29498                                                NaN
29499  https://p.scdn.co/mp3-preview/cb8fde6edc08e70a...
29500                                                NaN
29501  https://p.scdn.co/mp3-preview/1841a4034ba42fc0...
29502  https://p.scdn.co/mp3-preview/8d5174aeb7d6b740...

       spotify_track_duration_ms spotify_track_explicit  \
0                            NaN                    NaN
1                            NaN                    NaN
2                       166106.0                  False
3                       172066.0                  False
4                       211066.0                  False
...                          ...                    ...
29498                        NaN                    NaN
29499                   278429.0                   True
29500                        NaN                    NaN
29501                   264853.0                  False
29502                   273000.0                  False

                                  spotify_track_album  ...  loudness  mode  \
0                                                 NaN  ...       NaN   NaN
1                                                 NaN  ...       NaN   NaN
2                         The Essential Andy Williams  ...   -14.063   1.0
3                               Compelling Percussion  ...   -17.278   0.0
4      ...Baby One More Time (Digital Deluxe Version)  ...    -5.745   0.0
...                                               ...  ...       ...   ...
29498                                             NaN  ...       NaN   NaN
29499                                          FUTURE  ...    -7.673   1.0
29500                                             NaN  ...       NaN   NaN
29501                              !!!Going Places!!!  ...   -12.702   1.0
29502                              Swing Batta Swing!  ...    -9.642   1.0

       speechiness  acousticness  instrumentalness  liveness  valence  \
0              NaN           NaN               NaN       NaN      NaN
1              NaN           NaN               NaN       NaN      NaN
2           0.0315       0.91100          0.000267    0.1120    0.150
3           0.0361       0.00256          0.745000    0.1450    0.801
4           0.0307       0.20200          0.000131    0.4430    0.907
...            ...           ...               ...       ...      ...
29498          NaN           NaN               NaN       NaN      NaN
29499       0.4260       0.01450          0.000000    0.2630    0.627
29500          NaN           NaN               NaN       NaN      NaN
29501       0.3230       0.15400          0.279000    0.0584    0.192
29502       0.1400       0.04780          0.000363    0.0392    0.619

         tempo  time_signature  spotify_track_popularity
0          NaN             NaN                       NaN
1          NaN             NaN                       NaN
2       83.969             4.0                      38.0
3      121.962             4.0                      11.0
4       92.960             4.0                      77.0
...        ...             ...                       ...
29498      NaN             NaN                       NaN
29499  150.945             4.0                      51.0
29500      NaN             NaN                       NaN
29501   82.107             4.0                      35.0
29502  103.743             4.0                      28.0

[29503 rows x 23 columns]>

In [8]:
chart_history.columns

Index(['index', 'url', 'WeekID', 'Week Position', 'Song', 'Performer',
       'SongID', 'Instance', 'Previous Week Position', 'Peak Position',
       'Weeks on Chart'],
      dtype='str')

In [9]:
audio_features.columns

Index(['index', 'SongID', 'Performer', 'Song', 'spotify_genre',
       'spotify_track_id', 'spotify_track_preview_url',
       'spotify_track_duration_ms', 'spotify_track_explicit',
       'spotify_track_album', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'spotify_track_popularity'],
      dtype='str')

In [12]:
audio_features['danceability'].isna().sum()

np.int64(5169)

In [15]:
merge_df = pd.merge(chart_history, audio_features, on='SongID', how='left')

In [16]:
merge_df

,index_x,url,WeekID,Week Position,Song_x,Performer_x,SongID,Instance,Previous Week Position,Peak Position,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,spotify_track_popularity
0,0,http://www.billboard.com/charts/hot-100/1965-0...,7/17/1965,34,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,45.0,34,...,-15.044,1.0,0.0298,0.6100,0.000077,0.1000,0.568,82.331,3.0,21.0
1,1,http://www.billboard.com/charts/hot-100/1965-0...,7/24/1965,22,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,34.0,22,...,-15.044,1.0,0.0298,0.6100,0.000077,0.1000,0.568,82.331,3.0,21.0
2,2,http://www.billboard.com/charts/hot-100/1965-0...,7/31/1965,14,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,22.0,14,...,-15.044,1.0,0.0298,0.6100,0.000077,0.1000,0.568,82.331,3.0,21.0
3,3,http://www.billboard.com/charts/hot-100/1965-0...,8/7/1965,10,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,14.0,10,...,-15.044,1.0,0.0298,0.6100,0.000077,0.1000,0.568,82.331,3.0,21.0
4,4,http://www.billboard.com/charts/hot-100/1965-0...,8/14/1965,8,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,10.0,8,...,-15.044,1.0,0.0298,0.6100,0.000077,0.1000,0.568,82.331,3.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330456,327890,https://www.billboard.com/charts/hot-100/2018-...,10/20/2018,22,God Is A Woman,Ariana Grande,God Is A WomanAriana Grande,1,21.0,8,...,-5.934,1.0,0.0558,0.0233,0.000060,0.2370,0.268,145.031,4.0,62.0
330457,327891,http://www.billboard.com/charts/hot-100/1977-0...,5/21/1977,22,I Wanna Get Next To You,Rose Royce,I Wanna Get Next To YouRose Royce,1,10.0,10,...,-19.981,1.0,0.0314,0.8350,0.030000,0.0928,0.675,130.864,4.0,51.0
330458,327892,http://www.billboard.com/charts/hot-100/1981-0...,5/23/1981,22,I Can't Stand It,Eric Clapton And His Band,I Can't Stand ItEric Clapton And His Band,1,12.0,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330459,327893,http://www.billboard.com/charts/hot-100/1973-0...,9/29/1973,22,Here I Am Come & Take Me,Al Green,Here I Am Come & Take MeAl Green,1,16.0,10,...,-12.238,0.0,0.0364,0.3180,0.000084,0.0673,0.846,94.558,4.0,52.0
330460,327894,https://www.billboard.com/charts/hot-100/2020-...,11/28/2020,22,Hawai,Maluma & The Weeknd,HawaiMaluma & The Weeknd,1,12.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
audio_features['SongID'].duplicated().sum()

np.int64(117)

In [19]:
audio_features_clean = audio_features.drop_duplicates(subset='SongID')

In [20]:
audio_features_clean

,index,SongID,Performer,Song,spotify_genre,spotify_track_id,spotify_track_preview_url,spotify_track_duration_ms,spotify_track_explicit,spotify_track_album,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,spotify_track_popularity
0,0,-twistin'-White Silver SandsBill Black's Combo,Bill Black's Combo,-twistin'-White Silver Sands,[],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,¿Dònde Està Santa Claus? (Where Is Santa Claus...,Augie Rios,¿Dònde Està Santa Claus? (Where Is Santa Claus?),['novelty'],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,......And Roses And RosesAndy Williams,Andy Williams,......And Roses And Roses,"['adult standards', 'brill building pop', 'eas...",3tvqPPpXyIgKrm4PR9HCf0,https://p.scdn.co/mp3-preview/cef4883cfd1e0e53...,166106.0,False,The Essential Andy Williams,...,-14.063,1.0,0.0315,0.91100,0.000267,0.1120,0.150,83.969,4.0,38.0
3,3,...And Then There Were DrumsSandy Nelson,Sandy Nelson,...And Then There Were Drums,"['rock-and-roll', 'space age pop', 'surf music']",1fHHq3qHU8wpRKHzhojZ4a,NaN,172066.0,False,Compelling Percussion,...,-17.278,0.0,0.0361,0.00256,0.745000,0.1450,0.801,121.962,4.0,11.0
4,4,...Baby One More TimeBritney Spears,Britney Spears,...Baby One More Time,"['dance pop', 'pop', 'post-teen pop']",3MjUtNVVq3C8Fn0MP3zhXa,https://p.scdn.co/mp3-preview/da2134a161f1cb34...,211066.0,False,...Baby One More Time (Digital Deluxe Version),...,-5.745,0.0,0.0307,0.20200,0.000131,0.4430,0.907,92.960,4.0,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29498,29498,Zoo YorkLil Tjay Featuring Fivio Foreign & Pop...,Lil Tjay Featuring Fivio Foreign & Pop Smoke,Zoo York,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29499,29499,ZoomFuture,Future,Zoom,"['atl hip hop', 'hip hop', 'pop rap', 'rap', '...",2IG6Te7JyvrtqhFeOF7le4,https://p.scdn.co/mp3-preview/cb8fde6edc08e70a...,278429.0,True,FUTURE,...,-7.673,1.0,0.4260,0.01450,0.000000,0.2630,0.627,150.945,4.0,51.0
29500,29500,ZoomLil' Boosie Featuring Yung Joc,Lil' Boosie Featuring Yung Joc,Zoom,"['baton rouge rap', 'deep southern trap']",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29501,29501,Zorba The GreekHerb Alpert & The Tijuana Brass,Herb Alpert & The Tijuana Brass,Zorba The Greek,"['adult standards', 'easy listening', 'lounge']",3WLEVNohakzZmMpN5W7mHK,https://p.scdn.co/mp3-preview/1841a4034ba42fc0...,264853.0,False,!!!Going Places!!!,...,-12.702,1.0,0.3230,0.15400,0.279000,0.0584,0.192,82.107,4.0,35.0
29502,29502,Zunga ZengK7,K7,Zunga Zeng,['freestyle'],0XevPPcCBPovknaBw3lFvh,https://p.scdn.co/mp3-preview/8d5174aeb7d6b740...,273000.0,False,Swing Batta Swing!,...,-9.642,1.0,0.1400,0.04780,0.000363,0.0392,0.619,103.743,4.0,28.0

In [21]:
merged_df = pd.merge(chart_history, audio_features_clean, on='SongID', how='left')
print(merged_df.shape)

(327895, 33)

In [22]:
import os

# Create a data folder if it doesn't exist yet
os.makedirs('data', exist_ok=True)

# Save the merged dataset
merged_df.to_csv('data/billboard_merged.csv', index=False)

print("Saved to data/billboard_merged.csv")

Saved to data/billboard_merged.csv

DONE WITH SETUP AND FILES

STARTING SQL ANALYSIS

In [23]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:///data/ar_project.db')

merged_df.to_sql('billboard_history', con=engine, if_exists='replace', index=False)

327895

In [24]:
import pandas as pd

test_query = pd.read_sql("SELECT * FROM billboard_history LIMIT 5", con=engine)
print(test_query)

   index_x                                                url     WeekID  \
0        0  http://www.billboard.com/charts/hot-100/1965-0...  7/17/1965
1        1  http://www.billboard.com/charts/hot-100/1965-0...  7/24/1965
2        2  http://www.billboard.com/charts/hot-100/1965-0...  7/31/1965
3        3  http://www.billboard.com/charts/hot-100/1965-0...   8/7/1965
4        4  http://www.billboard.com/charts/hot-100/1965-0...  8/14/1965

   Week Position                  Song_x Performer_x  \
0             34  Don't Just Stand There  Patty Duke
1             22  Don't Just Stand There  Patty Duke
2             14  Don't Just Stand There  Patty Duke
3             10  Don't Just Stand There  Patty Duke
4              8  Don't Just Stand There  Patty Duke

                             SongID  Instance  Previous Week Position  \
0  Don't Just Stand TherePatty Duke         1                    45.0
1  Don't Just Stand TherePatty Duke         1                    34.0
2  Don't Just Stand TherePatty Duke         1                    22.0
3  Don't Just Stand TherePatty Duke         1                    14.0
4  Don't Just Stand TherePatty Duke         1                    10.0

   Peak Position  ...  loudness  mode speechiness acousticness  \
0             34  ...   -15.044   1.0      0.0298         0.61
1             22  ...   -15.044   1.0      0.0298         0.61
2             14  ...   -15.044   1.0      0.0298         0.61
3             10  ...   -15.044   1.0      0.0298         0.61
4              8  ...   -15.044   1.0      0.0298         0.61

  instrumentalness liveness valence   tempo  time_signature  \
0         0.000077      0.1   0.568  82.331             3.0
1         0.000077      0.1   0.568  82.331             3.0
2         0.000077      0.1   0.568  82.331             3.0
3         0.000077      0.1   0.568  82.331             3.0
4         0.000077      0.1   0.568  82.331             3.0

  spotify_track_popularity
0                     21.0
1                     21.0
2                     21.0
3                     21.0
4                     21.0

[5 rows x 33 columns]

In [25]:
merged_df.columns.tolist()

['index_x',
 'url',
 'WeekID',
 'Week Position',
 'Song_x',
 'Performer_x',
 'SongID',
 'Instance',
 'Previous Week Position',
 'Peak Position',
 'Weeks on Chart',
 'index_y',
 'Performer_y',
 'Song_y',
 'spotify_genre',
 'spotify_track_id',
 'spotify_track_preview_url',
 'spotify_track_duration_ms',
 'spotify_track_explicit',
 'spotify_track_album',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'time_signature',
 'spotify_track_popularity']

In [26]:
merged_df = merged_df.drop(columns=['index_x', 'index_y', 'Song_y', 'Performer_y'])

In [27]:
merged_df = merged_df.rename(columns={'Song_x': 'Song', 'Performer_x': 'Performer'})

In [28]:
print(merged_df.columns.tolist())

['url', 'WeekID', 'Week Position', 'Song', 'Performer', 'SongID', 'Instance', 'Previous Week Position', 'Peak Position', 'Weeks on Chart', 'spotify_genre', 'spotify_track_id', 'spotify_track_preview_url', 'spotify_track_duration_ms', 'spotify_track_explicit', 'spotify_track_album', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature', 'spotify_track_popularity']

In [29]:
merged_df.to_sql('billboard_history', con=engine, if_exists='replace', index=False)

327895

In [37]:
query1 = '''
SELECT Song, Performer, "Peak Position", "Weeks on Chart"
FROM billboard_history
WHERE "Peak Position" = 1
LIMIT 10
'''

result1 = pd.read_sql(query1, con = engine)

In [38]:
print(result1)

                                                Song  \
0                            Don't Leave Me This Way
1                            Don't Leave Me This Way
2                            Don't Leave Me This Way
3                            Don't Leave Me This Way
4                            Don't Leave Me This Way
5                            Don't Leave Me This Way
6                                   Poor Little Fool
7                                      One Sweet Day
8  Candle In The Wind 1997/Something About The Wa...
9                                Do I Make You Proud

                    Performer  Peak Position  Weeks on Chart
0              Thelma Houston              1              19
1              Thelma Houston              1              20
2              Thelma Houston              1              21
3              Thelma Houston              1              22
4              Thelma Houston              1              23
5              Thelma Houston              1              24
6                Ricky Nelson              1               1
7  Mariah Carey & Boyz II Men              1               1
8                  Elton John              1               1
9                Taylor Hicks              1               1

In [40]:
query2 = '''
SELECT Song, Performer, MAX("Weeks on Chart") AS total_weeks_charted
FROM billboard_history
WHERE "Peak Position" = 1
GROUP BY Song, Performer
ORDER BY total_weeks_charted DESC
LIMIT 10'''

result2 = pd.read_sql(query2, con = engine)
print(result2)

                           Song                                  Performer  \
0             Party Rock Anthem  LMFAO Featuring Lauren Bennett & GoonRock
1           Rolling In The Deep                                      Adele
2                       Circles                                Post Malone
3   Macarena (Bayside Boys Mix)                                Los Del Rio
4                     All Of Me                                John Legend
5  Somebody That I Used To Know                     Gotye Featuring Kimbra
6                  Shape Of You                                 Ed Sheeran
7                        Smooth               Santana Featuring Rob Thomas
8                    Dark Horse               Katy Perry Featuring Juicy J
9               I Gotta Feeling                        The Black Eyed Peas

   total_weeks_charted
0                   68
1                   65
2                   61
3                   60
4                   59
5                   59
6                   58
7                   58
8                   57
9                   56

In [44]:
inner_query = '''
SELECT SongID, MIN("Peak Position") AS highest_position, danceability, energy, tempo, valence
FROM billboard_history
WHERE danceability IS NOT NULL
GROUP BY SongID, danceability, energy, tempo, valence
'''

test = pd.read_sql(inner_query, con=engine)
print(test.shape)
print(test.head())

(24224, 6)
                                              SongID  highest_position  \
0                        "B" GirlsYoung And Restless                54
1  "Cherry Cherry" from Hot August NightNeil Diamond                31
2                              #1 Dee JayGoody Goody                82
3                                            #1Nelly                22
4                                #9 DreamJohn Lennon                 9

   danceability  energy    tempo  valence
0         0.615   0.497  193.762    0.769
1         0.340   0.948  172.349    0.604
2         0.859   0.376  127.202    0.902
3         0.792   0.600   89.985    0.463
4         0.406   0.597  115.474    0.478

In [47]:
query_final = '''
SELECT
    CASE
        WHEN highest_position <= 10 THEN 'Top 10'
        WHEN highest_position <= 40 THEN 'Top 40'
        ELSE 'Charted outside top 40'
        END as success_tier,
        AVG(danceability) AS avg_danceability,
        AVG(energy) AS avg_energy,
        AVG(tempo) AS avg_tempo,
        AVG(valence) AS avg_valence,
        COUNT(*) AS num_songs
        
FROM (
    SELECT 
        SongID,
        MIN("Peak Position") AS highest_position,
        danceability,
        energy,
        tempo,
        valence
    FROM billboard_history
    WHERE danceability IS NOT NULL
    GROUP BY SongID, danceability, energy, tempo, valence
) AS unique_songs
GROUP BY success_tier
ORDER BY avg_danceability DESC'''

result_final = pd.read_sql(query_final, con=engine)
print(result_final)

             success_tier  avg_danceability  avg_energy   avg_tempo  \
0                  Top 10          0.617060    0.609917  119.302363
1                  Top 40          0.595877    0.617801  120.317905
2  Charted outside top 40          0.595509    0.621071  120.614074

   avg_valence  num_songs
0     0.624523       4480
1     0.605631       7099
2     0.592048      12645

In [54]:
query_2010 = '''
SELECT 
    CASE
        WHEN highest_position <= 10 THEN 'Top 10'
        WHEN highest_position <= 40 THEN 'Top 40'
        ELSE 'Charted outside top 40' 
    END AS success_tier,
    AVG(danceability) AS avg_danceability,
    AVG(energy) AS avg_energy,
    AVG(tempo) AS avg_tempo,
    AVG(valence) AS avg_valence,
    COUNT(*) as num_songs

FROM (
    SELECT
        SongID,
        MIN("Peak Position") AS highest_position,
        danceability,
        energy,
        tempo,
        valence
    FROM billboard_history
    WHERE danceability IS NOT NULL
    AND CAST(SUBSTR(WeekID, -4) AS INTEGER) >= 2010
    GROUP BY SongID, danceability, energy, tempo, valence
    ) AS unique_songs
    GROUP BY success_tier
    ORDER BY avg_danceability DESC
'''
result_2010 = pd.read_sql(query_2010, con=engine)
print(result_2010)

             success_tier  avg_danceability  avg_energy   avg_tempo  \
0                  Top 10          0.672339    0.670513  121.515607
1                  Top 40          0.642263    0.661425  122.596040
2  Charted outside top 40          0.633286    0.661568  124.015812

   avg_valence  num_songs
0     0.518644        563
1     0.476206       1261
2     0.470284       3079

In [ ]:
query_2020 = '''
SELECT 
    CASE
        WHEN highest_position <= 10 THEN 'Top 10'
        WHEN highest_position <= 40 THEN 'Top 40'
        ELSE 'Charted outside top 40' 
    END AS success_tier,
    AVG(danceability) AS avg_danceability,
    AVG(energy) AS avg_energy,
    AVG(tempo) AS avg_tempo,
    AVG(valence) AS avg_valence,
    COUNT(*) as num_songs

FROM (
    SELECT
        SongID,
        MIN("Peak Position") AS highest_position,
        danceability,
        energy,
        tempo,
        valence
    FROM billboard_history
    WHERE danceability IS NOT NULL
    AND CAST(SUBSTR(WeekID, -4) AS INTEGER) >= 2020
    GROUP BY SongID, danceability, energy, tempo, valence
    ) AS unique_songs
    GROUP BY success_tier
    ORDER BY avg_danceability DESC
'''
result_2020 = pd.read_sql(query_2020, con=engine)
print(result_2020)

             success_tier  avg_danceability  avg_energy   avg_tempo  \
0  Charted outside top 40          0.669514    0.623880  123.525447
1                  Top 10          0.660513    0.589037  127.574387
2                  Top 40          0.660257    0.593178  119.172942

   avg_valence  num_songs
0     0.471662        432
1     0.504032         80
2     0.480220        191

In [59]:
query_decade = '''
SELECT 
    decade,
    CASE
        WHEN highest_position <= 10 THEN 'Top 10'
        WHEN highest_position <= 40 THEN 'Top 40'
        ELSE 'Charted outside top 40' 
    END AS success_tier,
    AVG(danceability) AS avg_danceability,
    AVG(energy) AS avg_energy,
    AVG(tempo) AS avg_tempo,
    AVG(valence) AS avg_valence,
    COUNT(*) as num_songs

FROM (
    SELECT
        SongID,
        MIN("Peak Position") AS highest_position,
        danceability,
        energy,
        tempo,
        valence,
        (CAST(SUBSTR(WeekID, -4) AS INTEGER) / 10) * 10 AS decade
    FROM billboard_history
    WHERE danceability IS NOT NULL
    AND (CAST(SUBSTR(WeekID, -4) AS INTEGER) / 10) * 10 IN (2000,2010,2020)
    GROUP BY SongID, danceability, energy, tempo, valence
    ) AS unique_songs
    GROUP BY decade, success_tier
    ORDER BY decade, success_tier 
'''
result_decade = pd.read_sql(query_decade, con=engine)
print(result_decade)

   decade            success_tier  avg_danceability  avg_energy   avg_tempo  \
0    2000  Charted outside top 40          0.605890    0.721000  122.581951
1    2000                  Top 10          0.672553    0.703160  118.347936
2    2000                  Top 40          0.627280    0.711954  118.547664
3    2010  Charted outside top 40          0.628691    0.666522  124.029311
4    2010                  Top 10          0.673333    0.678877  120.781115
5    2010                  Top 40          0.641553    0.670265  123.075230
6    2020  Charted outside top 40          0.668015    0.622838  123.961311
7    2020                  Top 10          0.673194    0.592516  128.962742
8    2020                  Top 40          0.653297    0.592709  119.947593

   avg_valence  num_songs
0     0.538006       1606
1     0.582891        564
2     0.556170        985
3     0.469856       2651
4     0.516816        487
5     0.478109       1065
6     0.470069        405
7     0.528605         62
8     0.466721        172